name: CI
on:
  push:
  pull_request:

jobs:
  build-linux:
    uses: ./.github/workflows/build_linux.yml
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build_macos.yml
    secrets: inherit

  build-windows:
    uses: ./.github/workflows/build_windows.yml
    secrets: inherit
